name = "main-website"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION="22.12.0"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_c29jaWFsLWFhcmR2YXJrLTQ2LmNsZXJrLmFjY291bnRzLmRldiQ"
NEXT_PUBLIC_SUPABASE_URL="https://etnefrxqgammemklhhrd.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0bmVmcnhxZ2FtbWVta2xoaHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg2Nzk0ODgsImV4cCI6MjA0NDI1NTQ4OH0.mC8GPKJSmlTywwh3ewebpq5bv4NZVbcZ-4VUPAEqZUU"
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=http://test.ecellmjcet.com/Dashboard
NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=http://test.ecellmjcet.com/Dashboard