name = "main-website"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION="22.12.0"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_c29jaWFsLWFhcmR2YXJrLTQ2LmNsZXJrLmFjY291bnRzLmRldiQ
