import type { Metadata } from "next";
import { Doto, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const doto = Doto({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-doto",
});

const inter = Inter({
  subsets: ["latin"], // Only include the Latin subset
  weight: ["400", "600"], // Choose specific weights you need
  variable: "--font-inter", // Custom CSS variable
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${doto.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
